# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{segments}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh McArthur"]
  s.date = %q{2011-06-04}
  s.description = %q{A Rails 3 Engine for managing and rendering text segments into your Rails web application. Segments are short-to-medium blocks of text or HTML that you wish to use throughout your application. It includes a web interface for managing segments, and is automatically compatible with Internationalization (I18n)}
  s.email = %q{joshua.mcarthur@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/controllers/segments_controller.rb",
    "app/models/segment.rb",
    "app/views/layouts/segment_layout.html.erb",
    "app/views/segments/_form.html.erb",
    "app/views/segments/_segment_row.html.erb",
    "app/views/segments/edit.html.erb",
    "app/views/segments/index.html.erb",
    "app/views/segments/show.html.erb",
    "config/boot.rb",
    "config/locales/en.yml",
    "config/routes.rb",
    "lib/engine.rb",
    "lib/generators/segments/segments_generator.rb",
    "lib/generators/segments/templates/segments_migration.rb",
    "lib/segments.rb",
    "lib/tasks/segments.rake",
    "segments.gemspec"
  ]
  s.homepage = %q{http://github.com/joshmcarthur/segments}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{A Rails 3 Engine for managing text segments}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<git>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<git>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<git>, [">= 0"])
  end
end

